* Question :drill:
Anecdotal evidence?

** Answer
Evidence, often personal, that is collected casually rather than by a well-designed study.

* Question :drill:
Population?

** Answer
A group we are interested in studying. "Population" often refers to a group of people, but the term is used for other subjects, too.


* Question :drill:
Cross-sectional study?

** Answer
A study that collects data about a population at a particular point in time.
* Question :drill:
Cycle?

** Answer
In a repeated cross-sectional study, each repetition of the study is called a cycle

* Question :drill:
longitudinal study?

** Answer
A study that follows a population over time, collecting data from the same group repeatedly

* Question :drill:
Record?

** Answer
In a dataset, a collection of information about a single person or subject
* Question :drill:
Respondent?

** Answer
A person who responds to a survey

* Question :drill:
Sample?

** Answer
The subset of a population used to collect data

* Question :drill:
Representative?

** Answer
A sample is representative if every member of the population has the same chance of being in the sample

* Question :drill:
Oversampling?

** Answer
The technique of increasing the representation of a subpopulation in order to avoid 
errors due to small sample size

* Question :drill:
Raw data?

** Answer
Values collected and recorded with little or no checking, calculation or interpretation

* Question :drill:
recode?

** Answer
A value that is generated by calculation and other logic applied to raw data

* Question :drill:
Data cleaning?

** Answer
Process that include validating data, identifying errors, translating between data
types and representation
